package dats.model.common;

import java.sql.Timestamp;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 12 18:30:46 EAT 2017
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void insertDaTrackingUpdate(int daNumberId, int stepId, Timestamp date, int statusId, String comments);

    boolean updateStep1(String daNumber, String comments);

    boolean updateStep2(String oldDaNumber, String newDaNumber, float totalValue, int numberOfBeneficiaries,
                        int districtId, String comments, int userId, int daId);


    boolean insertRequestDaFileDetails(int stepId, int daId, String documentName, String documentLocation,
                                       String description);


    boolean isInsertDaStepIsSuccessful();

    boolean insertDaStepDetailsProgress(int stepId, int userId, String loggedInUserFullname, int daId, String comments);

    boolean insertGenerateDaDetails(float totalValue, int beneficiariesNumber, int districtId, int ngoId,
                                    int interventionTypeId, int phaseId, String daNumber, String loaNumber,
                                    String comments, String loggedInUserFullname, int userId);

   // float getRateValue(int rateId);
}

