package dats.model.common;

import java.sql.Timestamp;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 16 12:54:09 EAT 2017
// ---------------------------------------------------------------------
public interface DaTrackingProcessViewRow extends Row {
    Integer getId();

    void setId(Integer value);

    Integer getDaId();

    void setDaId(Integer value);

    Integer getDaStatusId();

    void setDaStatusId(Integer value);

    Integer getStepId();

    void setStepId(Integer value);

    Integer getUserId();

    void setUserId(Integer value);

    Timestamp getDateEntered();

    void setDateEntered(Timestamp value);

    String getComments();

    void setComments(String value);

    Integer getIsActive();

    void setIsActive(Integer value);
}

