package dats.model.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 13 11:53:18 EAT 2017
// ---------------------------------------------------------------------
public interface LoginUsersViewRow extends Row {
    String getUsername();

    void setUsername(String value);

    String getPassWord();

    void setPassWord(String value);

    String getDescription();

    void setDescription(String value);
}

