package dats.model.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 12 11:23:08 EAT 2017
// ---------------------------------------------------------------------
public interface RatesViewRow extends Row {
    Integer getId();

    void setId(Integer value);

    Float getRate();

    void setRate(Float value);

    String getDescription();

    void setDescription(String value);
}

