package dats.model.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 23 12:17:19 EAT 2017
// ---------------------------------------------------------------------
public interface StepResponsiblePersonsViewRow extends Row {
    Integer getId();

    void setId(Integer value);

    Integer getStepId();

    void setStepId(Integer value);

    Integer getUserId();

    void setUserId(Integer value);

    Boolean getIsActive();

    void setIsActive(Boolean value);

    String getComments();

    void setComments(String value);
}

