package dats.model.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 12 18:19:15 EAT 2017
// ---------------------------------------------------------------------
public interface UsersViewRow extends Row {
    String getDescription();

    String getEmail();

    String getFirstname();

    String getGender();

    Integer getGroupId();

    Integer getId();

    Integer getIsActive();

    String getLastname();

    String getOthername();

    String getPassword();

    String getPhoneMobile();

    String getPhoneOffice();

    Integer getUnitId();

    String getUsername();

    void setDescription(String value);

    void setEmail(String value);

    void setFirstname(String value);

    void setGender(String value);

    void setGroupId(Integer value);

    void setId(Integer value);

    void setIsActive(Integer value);

    void setLastname(String value);

    void setOthername(String value);

    void setPassword(String value);

    void setPhoneMobile(String value);

    void setPhoneOffice(String value);

    void setUnitId(Integer value);

    void setUsername(String value);
}

