package dats.model;

import java.sql.JDBCType;
import java.sql.Timestamp;
import dats.model.common.AppModule;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import oracle.jbo.ApplicationModule;
import oracle.jbo.Row;
import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.ViewObject;
import oracle.jbo.client.Configuration;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
import org.eclipse.persistence.platform.database.jdbc.JDBCTypes;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jun 23 11:21:30 EAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    private boolean insertDaStepIsSuccessful = false;
    public AppModuleImpl() {
       
    }

    /**
     * Container's getter for DaStatusesView1.
     * @return DaStatusesView1
     */
    public ViewObjectImpl getDaStatusesView1() {
        return (ViewObjectImpl) findViewObject("DaStatusesView1");
    }

    /**
     * Container's getter for DaTrackingProcessDocumentsView1.
     * @return DaTrackingProcessDocumentsView1
     */
    public DaTrackingProcessDocumentsViewImpl getDaTrackingProcessDocumentsView1() {
        return (DaTrackingProcessDocumentsViewImpl) findViewObject("DaTrackingProcessDocumentsView1");
    }

    /**
     * Container's getter for DaTrackingProcessView1.
     * @return DaTrackingProcessView1
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView1() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView1");
    }

    /**
     * Container's getter for DisbursementAuthorizationsView1.
     * @return DisbursementAuthorizationsView1
     */
    public DisbursementAuthorizationsViewImpl getDisbursementAuthorizationsView1() {
        return (DisbursementAuthorizationsViewImpl) findViewObject("DisbursementAuthorizationsView1");
    }


    /**
     * Container's getter for GroupsView1.
     * @return GroupsView1
     */
    public ViewObjectImpl getGroupsView1() {
        return (ViewObjectImpl) findViewObject("GroupsView1");
    }

    /**
     * Container's getter for StepsView1.
     * @return StepsView1
     */
    public ViewObjectImpl getStepsView1() {
        return (ViewObjectImpl) findViewObject("StepsView1");
    }

    /**
     * Container's getter for UnitsView1.
     * @return UnitsView1
     */
    public ViewObjectImpl getUnitsView1() {
        return (ViewObjectImpl) findViewObject("UnitsView1");
    }

    /**
     * Container's getter for UsersView1.
     * @return UsersView1
     */
    public UsersViewImpl getUsersView1() {
        return (UsersViewImpl) findViewObject("UsersView1");
    }

    /**
     * Container's getter for DaTrackingProcessView2.
     * @return DaTrackingProcessView2
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView2() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView2");
    }

    /**
     * Container's getter for DaTrackingProcessView3.
     * @return DaTrackingProcessView3
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView3() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView3");
    }

    /**
     * Container's getter for DaTrackingProcessView4.
     * @return DaTrackingProcessView4
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView4() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView4");
    }

    /**
     * Container's getter for DaTrackingProcessView5.
     * @return DaTrackingProcessView5
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView5() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView5");
    }

    /**
     * Container's getter for DaTrackingProcessView6.
     * @return DaTrackingProcessView6
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView6() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView6");
    }

    /**
     * Container's getter for DaTrackingProcessView7.
     * @return DaTrackingProcessView7
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView7() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView7");
    }

    /**
     * Container's getter for DaTrackingProcessView8.
     * @return DaTrackingProcessView8
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView8() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView8");
    }

    /**
     * Container's getter for DaTrackingProcessView9.
     * @return DaTrackingProcessView9
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView9() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView9");
    }


    /**
     * Container's getter for DaTrackingProcessDocumentsView3.
     * @return DaTrackingProcessDocumentsView3
     */
    public DaTrackingProcessDocumentsViewImpl getDaTrackingProcessDocumentsView3() {
        return (DaTrackingProcessDocumentsViewImpl) findViewObject("DaTrackingProcessDocumentsView3");
    }

    /**
     * Container's getter for DaTrackingProcessView10.
     * @return DaTrackingProcessView10
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView10() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView10");
    }

    /**
     * Container's getter for DaTrackingProcessView11.
     * @return DaTrackingProcessView11
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView11() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView11");
    }

    /**
     * Container's getter for DaTrackingProcessView12.
     * @return DaTrackingProcessView12
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView12() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView12");
    }

    /**
     * Container's getter for DaTrackingProcessView13.
     * @return DaTrackingProcessView13
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView13() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView13");
    }

    /**
     * Container's getter for DaTrackingProcessDocumentsView4.
     * @return DaTrackingProcessDocumentsView4
     */
    public DaTrackingProcessDocumentsViewImpl getDaTrackingProcessDocumentsView4() {
        return (DaTrackingProcessDocumentsViewImpl) findViewObject("DaTrackingProcessDocumentsView4");
    }

    /**
     * Container's getter for DaTrackingProcessDocumentsView5.
     * @return DaTrackingProcessDocumentsView5
     */
    public DaTrackingProcessDocumentsViewImpl getDaTrackingProcessDocumentsView5() {
        return (DaTrackingProcessDocumentsViewImpl) findViewObject("DaTrackingProcessDocumentsView5");
    }


    /**
     * Container's getter for DaTrackingProcessDocumentsView9.
     * @return DaTrackingProcessDocumentsView9
     */
    public DaTrackingProcessDocumentsViewImpl getDaTrackingProcessDocumentsView9() {
        return (DaTrackingProcessDocumentsViewImpl) findViewObject("DaTrackingProcessDocumentsView9");
    }

    /**
     * Container's getter for DaTrackingProcessView14.
     * @return DaTrackingProcessView14
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView14() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView14");
    }

    /**
     * Container's getter for DaTrackingProcessView15.
     * @return DaTrackingProcessView15
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView15() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView15");
    }

    /**
     * Container's getter for DaTrackingProcessView16.
     * @return DaTrackingProcessView16
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView16() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView16");
    }

    /**
     * Container's getter for DaTrackingProcessView17.
     * @return DaTrackingProcessView17
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView17() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView17");
    }


    /**
     * Container's getter for DaTrackingProcessDocumentsView13.
     * @return DaTrackingProcessDocumentsView13
     */
    public DaTrackingProcessDocumentsViewImpl getDaTrackingProcessDocumentsView13() {
        return (DaTrackingProcessDocumentsViewImpl) findViewObject("DaTrackingProcessDocumentsView13");
    }

    /**
     * Container's getter for DaTrackingProcessView22.
     * @return DaTrackingProcessView22
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView22() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView22");
    }

    /**
     * Container's getter for DaTrackingProcessView23.
     * @return DaTrackingProcessView23
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView23() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView23");
    }

    /**
     * Container's getter for DaTrackingProcessView24.
     * @return DaTrackingProcessView24
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView24() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView24");
    }

    /**
     * Container's getter for DaTrackingProcessView25.
     * @return DaTrackingProcessView25
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView25() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView25");
    }


    /**
     * Container's getter for DaTrackingProcessDocumentsView15.
     * @return DaTrackingProcessDocumentsView15
     */
    public DaTrackingProcessDocumentsViewImpl getDaTrackingProcessDocumentsView15() {
        return (DaTrackingProcessDocumentsViewImpl) findViewObject("DaTrackingProcessDocumentsView15");
    }

    /**
     * Container's getter for DaTrackingProcessView26.
     * @return DaTrackingProcessView26
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView26() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView26");
    }

    /**
     * Container's getter for DaTrackingProcessView27.
     * @return DaTrackingProcessView27
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView27() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView27");
    }

    /**
     * Container's getter for DaTrackingProcessView28.
     * @return DaTrackingProcessView28
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView28() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView28");
    }

    /**
     * Container's getter for DaTrackingProcessView29.
     * @return DaTrackingProcessView29
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView29() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView29");
    }


    /**
     * Container's getter for DaTrackingProcessDocumentsView17.
     * @return DaTrackingProcessDocumentsView17
     */
    public DaTrackingProcessDocumentsViewImpl getDaTrackingProcessDocumentsView17() {
        return (DaTrackingProcessDocumentsViewImpl) findViewObject("DaTrackingProcessDocumentsView17");
    }

    /**
     * Container's getter for DaTrackingProcessView30.
     * @return DaTrackingProcessView30
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView30() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView30");
    }

    /**
     * Container's getter for DaTrackingProcessView31.
     * @return DaTrackingProcessView31
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView31() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView31");
    }

    /**
     * Container's getter for DaTrackingProcessView32.
     * @return DaTrackingProcessView32
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView32() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView32");
    }

    /**
     * Container's getter for DaTrackingProcessView33.
     * @return DaTrackingProcessView33
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView33() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView33");
    }


    /**
     * Container's getter for UsersView3.
     * @return UsersView3
     */
    public UsersViewImpl getUsersView3() {
        return (UsersViewImpl) findViewObject("UsersView3");
    }

    /**
     * Container's getter for UsersView4.
     * @return UsersView4
     */
    public UsersViewImpl getUsersView4() {
        return (UsersViewImpl) findViewObject("UsersView4");
    }

    /**
     * Container's getter for UsersView5.
     * @return UsersView5
     */
    public UsersViewImpl getUsersView5() {
        return (UsersViewImpl) findViewObject("UsersView5");
    }

    /**
     * Container's getter for UsersView6.
     * @return UsersView6
     */
    public UsersViewImpl getUsersView6() {
        return (UsersViewImpl) findViewObject("UsersView6");
    }

    /**
     * Container's getter for UsersView7.
     * @return UsersView7
     */
    public UsersViewImpl getUsersView7() {
        return (UsersViewImpl) findViewObject("UsersView7");
    }

    /**
     * Container's getter for UsersView8.
     * @return UsersView8
     */
    public UsersViewImpl getUsersView8() {
        return (UsersViewImpl) findViewObject("UsersView8");
    }

    /**
     * Container's getter for UsersView9.
     * @return UsersView9
     */
    public UsersViewImpl getUsersView9() {
        return (UsersViewImpl) findViewObject("UsersView9");
    }


    /**
     * Container's getter for UsersView11.
     * @return UsersView11
     */
    public UsersViewImpl getUsersView11() {
        return (UsersViewImpl) findViewObject("UsersView11");
    }

    /**
     * Container's getter for UsersView12.
     * @return UsersView12
     */
    public UsersViewImpl getUsersView12() {
        return (UsersViewImpl) findViewObject("UsersView12");
    }

    /**
     * Container's getter for UsersView13.
     * @return UsersView13
     */
    public UsersViewImpl getUsersView13() {
        return (UsersViewImpl) findViewObject("UsersView13");
    }

    /**
     * Container's getter for UsersView14.
     * @return UsersView14
     */
    public UsersViewImpl getUsersView14() {
        return (UsersViewImpl) findViewObject("UsersView14");
    }

    /**
     * Container's getter for UsersView15.
     * @return UsersView15
     */
    public UsersViewImpl getUsersView15() {
        return (UsersViewImpl) findViewObject("UsersView15");
    }

    /**
     * Container's getter for UsersView16.
     * @return UsersView16
     */
    public UsersViewImpl getUsersView16() {
        return (UsersViewImpl) findViewObject("UsersView16");
    }

    /**
     * Container's getter for UsersView17.
     * @return UsersView17
     */
    public UsersViewImpl getUsersView17() {
        return (UsersViewImpl) findViewObject("UsersView17");
    }

    /**
     * Container's getter for FkDaTrackingProcessUsersLink1.
     * @return FkDaTrackingProcessUsersLink1
     */
    public ViewLinkImpl getFkDaTrackingProcessUsersLink1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessUsersLink1");
    }

    /**
     * Container's getter for FkDaTrackingProcessStepsLink1.
     * @return FkDaTrackingProcessStepsLink1
     */
    public ViewLinkImpl getFkDaTrackingProcessStepsLink1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessStepsLink1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDisbursementAuthoizationsLink1.
     * @return FkDaTrackingProcessDisbursementAuthoizationsLink1
     */
    public ViewLinkImpl getFkDaTrackingProcessDisbursementAuthoizationsLink1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDisbursementAuthoizationsLink1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDaStatusesLink1.
     * @return FkDaTrackingProcessDaStatusesLink1
     */
    public ViewLinkImpl getFkDaTrackingProcessDaStatusesLink1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDaStatusesLink1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDaStatusesAssoc1Link1.
     * @return FkDaTrackingProcessDaStatusesAssoc1Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDaStatusesAssoc1Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDaStatusesAssoc1Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDisbursementAuthoizationsAssoc1Link1.
     * @return FkDaTrackingProcessDisbursementAuthoizationsAssoc1Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDisbursementAuthoizationsAssoc1Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDisbursementAuthoizationsAssoc1Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessStepsAssoc1Link1.
     * @return FkDaTrackingProcessStepsAssoc1Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessStepsAssoc1Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessStepsAssoc1Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessUsersAssoc1Link1.
     * @return FkDaTrackingProcessUsersAssoc1Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessUsersAssoc1Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessUsersAssoc1Link1");
    }


    /**
     * Container's getter for FkDaTrackingProcessDocumentsDaTrackingProcessLink1.
     * @return FkDaTrackingProcessDocumentsDaTrackingProcessLink1
     */
    public ViewLinkImpl getFkDaTrackingProcessDocumentsDaTrackingProcessLink1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDocumentsDaTrackingProcessLink1");
    }

    /**
     * Container's getter for FkDaTrackingProcessUsersAssoc2Link1.
     * @return FkDaTrackingProcessUsersAssoc2Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessUsersAssoc2Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessUsersAssoc2Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessStepsAssoc2Link1.
     * @return FkDaTrackingProcessStepsAssoc2Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessStepsAssoc2Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessStepsAssoc2Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDisbursementAuthoizationsAssoc2Link1.
     * @return FkDaTrackingProcessDisbursementAuthoizationsAssoc2Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDisbursementAuthoizationsAssoc2Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDisbursementAuthoizationsAssoc2Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDaStatusesAssoc2Link1.
     * @return FkDaTrackingProcessDaStatusesAssoc2Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDaStatusesAssoc2Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDaStatusesAssoc2Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDocumentsDaTrackingProcessAssoc1Link1.
     * @return FkDaTrackingProcessDocumentsDaTrackingProcessAssoc1Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDocumentsDaTrackingProcessAssoc1Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDocumentsDaTrackingProcessAssoc1Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDocumentsDaTrackingProcessAssoc2Link1.
     * @return FkDaTrackingProcessDocumentsDaTrackingProcessAssoc2Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDocumentsDaTrackingProcessAssoc2Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDocumentsDaTrackingProcessAssoc2Link1");
    }


    /**
     * Container's getter for FkDaTrackingProcessDocumentsDaTrackingProcessAssoc3Link1.
     * @return FkDaTrackingProcessDocumentsDaTrackingProcessAssoc3Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDocumentsDaTrackingProcessAssoc3Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDocumentsDaTrackingProcessAssoc3Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessUsersAssoc3Link1.
     * @return FkDaTrackingProcessUsersAssoc3Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessUsersAssoc3Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessUsersAssoc3Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessStepsAssoc3Link1.
     * @return FkDaTrackingProcessStepsAssoc3Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessStepsAssoc3Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessStepsAssoc3Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDisbursementAuthoizationsAssoc3Link1.
     * @return FkDaTrackingProcessDisbursementAuthoizationsAssoc3Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDisbursementAuthoizationsAssoc3Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDisbursementAuthoizationsAssoc3Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDaStatusesAssoc3Link1.
     * @return FkDaTrackingProcessDaStatusesAssoc3Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDaStatusesAssoc3Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDaStatusesAssoc3Link1");
    }


    /**
     * Container's getter for FkDaTrackingProcessDocumentsDaTrackingProcessAssoc5Link1.
     * @return FkDaTrackingProcessDocumentsDaTrackingProcessAssoc5Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDocumentsDaTrackingProcessAssoc5Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDocumentsDaTrackingProcessAssoc5Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessUsersAssoc5Link1.
     * @return FkDaTrackingProcessUsersAssoc5Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessUsersAssoc5Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessUsersAssoc5Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessStepsAssoc5Link1.
     * @return FkDaTrackingProcessStepsAssoc5Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessStepsAssoc5Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessStepsAssoc5Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDisbursementAuthoizationsAssoc5Link1.
     * @return FkDaTrackingProcessDisbursementAuthoizationsAssoc5Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDisbursementAuthoizationsAssoc5Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDisbursementAuthoizationsAssoc5Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDaStatusesAssoc5Link1.
     * @return FkDaTrackingProcessDaStatusesAssoc5Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDaStatusesAssoc5Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDaStatusesAssoc5Link1");
    }


    /**
     * Container's getter for FkDaTrackingProcessDocumentsDaTrackingProcessAssoc6Link1.
     * @return FkDaTrackingProcessDocumentsDaTrackingProcessAssoc6Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDocumentsDaTrackingProcessAssoc6Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDocumentsDaTrackingProcessAssoc6Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessUsersAssoc6Link1.
     * @return FkDaTrackingProcessUsersAssoc6Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessUsersAssoc6Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessUsersAssoc6Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessStepsAssoc6Link1.
     * @return FkDaTrackingProcessStepsAssoc6Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessStepsAssoc6Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessStepsAssoc6Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDisbursementAuthoizationsAssoc6Link1.
     * @return FkDaTrackingProcessDisbursementAuthoizationsAssoc6Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDisbursementAuthoizationsAssoc6Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDisbursementAuthoizationsAssoc6Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDaStatusesAssoc6Link1.
     * @return FkDaTrackingProcessDaStatusesAssoc6Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDaStatusesAssoc6Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDaStatusesAssoc6Link1");
    }


    /**
     * Container's getter for FkDaTrackingProcessDocumentsDaTrackingProcessAssoc7Link1.
     * @return FkDaTrackingProcessDocumentsDaTrackingProcessAssoc7Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDocumentsDaTrackingProcessAssoc7Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDocumentsDaTrackingProcessAssoc7Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessUsersAssoc7Link1.
     * @return FkDaTrackingProcessUsersAssoc7Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessUsersAssoc7Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessUsersAssoc7Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessStepsAssoc7Link1.
     * @return FkDaTrackingProcessStepsAssoc7Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessStepsAssoc7Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessStepsAssoc7Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDisbursementAuthoizationsAssoc7Link1.
     * @return FkDaTrackingProcessDisbursementAuthoizationsAssoc7Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDisbursementAuthoizationsAssoc7Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDisbursementAuthoizationsAssoc7Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDaStatusesAssoc7Link1.
     * @return FkDaTrackingProcessDaStatusesAssoc7Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDaStatusesAssoc7Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDaStatusesAssoc7Link1");
    }


    /**
     * Container's getter for FkUsersGroupsAssoc1Link1.
     * @return FkUsersGroupsAssoc1Link1
     */
    public ViewLinkImpl getFkUsersGroupsAssoc1Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersGroupsAssoc1Link1");
    }

    /**
     * Container's getter for FkUsersGroupsAssoc2Link1.
     * @return FkUsersGroupsAssoc2Link1
     */
    public ViewLinkImpl getFkUsersGroupsAssoc2Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersGroupsAssoc2Link1");
    }

    /**
     * Container's getter for FkUsersGroupsAssoc3Link1.
     * @return FkUsersGroupsAssoc3Link1
     */
    public ViewLinkImpl getFkUsersGroupsAssoc3Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersGroupsAssoc3Link1");
    }

    /**
     * Container's getter for FkUsersGroupsAssoc4Link1.
     * @return FkUsersGroupsAssoc4Link1
     */
    public ViewLinkImpl getFkUsersGroupsAssoc4Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersGroupsAssoc4Link1");
    }

    /**
     * Container's getter for FkUsersGroupsAssoc5Link1.
     * @return FkUsersGroupsAssoc5Link1
     */
    public ViewLinkImpl getFkUsersGroupsAssoc5Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersGroupsAssoc5Link1");
    }

    /**
     * Container's getter for FkUsersGroupsAssoc6Link1.
     * @return FkUsersGroupsAssoc6Link1
     */
    public ViewLinkImpl getFkUsersGroupsAssoc6Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersGroupsAssoc6Link1");
    }

    /**
     * Container's getter for FkUsersGroupsAssoc7Link1.
     * @return FkUsersGroupsAssoc7Link1
     */
    public ViewLinkImpl getFkUsersGroupsAssoc7Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersGroupsAssoc7Link1");
    }


    /**
     * Container's getter for FkUsersUnitsAssoc1Link1.
     * @return FkUsersUnitsAssoc1Link1
     */
    public ViewLinkImpl getFkUsersUnitsAssoc1Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersUnitsAssoc1Link1");
    }

    /**
     * Container's getter for FkUsersUnitsAssoc2Link1.
     * @return FkUsersUnitsAssoc2Link1
     */
    public ViewLinkImpl getFkUsersUnitsAssoc2Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersUnitsAssoc2Link1");
    }

    /**
     * Container's getter for FkUsersUnitsAssoc3Link1.
     * @return FkUsersUnitsAssoc3Link1
     */
    public ViewLinkImpl getFkUsersUnitsAssoc3Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersUnitsAssoc3Link1");
    }

    /**
     * Container's getter for FkUsersUnitsAssoc4Link1.
     * @return FkUsersUnitsAssoc4Link1
     */
    public ViewLinkImpl getFkUsersUnitsAssoc4Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersUnitsAssoc4Link1");
    }

    /**
     * Container's getter for FkUsersUnitsAssoc5Link1.
     * @return FkUsersUnitsAssoc5Link1
     */
    public ViewLinkImpl getFkUsersUnitsAssoc5Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersUnitsAssoc5Link1");
    }

    /**
     * Container's getter for FkUsersUnitsAssoc6Link1.
     * @return FkUsersUnitsAssoc6Link1
     */
    public ViewLinkImpl getFkUsersUnitsAssoc6Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersUnitsAssoc6Link1");
    }

    /**
     * Container's getter for FkUsersUnitsAssoc7Link1.
     * @return FkUsersUnitsAssoc7Link1
     */
    public ViewLinkImpl getFkUsersUnitsAssoc7Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersUnitsAssoc7Link1");
    }

    //Insert documents data
    /*   public void insertDocumentsData(String documentName, String documentLocation) {
        ViewObject vo = this.getDocumentsView1();
        Row row = vo.createRow();
        row.setAttribute("DocumentName", documentName);
        row.setAttribute("DocumentLocation", documentLocation);
        vo.insertRow(row);
        this.getDBTransaction().commit();
    }
*/
    //Insert DA tracking process documents details
    public void insertDaTrackingProcessDocumentsData(int documentId, int daTrackingProcessId) {
        ViewObject vo = this.getDaTrackingProcessDocumentsView1();
        Row row = vo.createRow();
        row.setAttribute("DocumentId", documentId);
        row.setAttribute("DaTrackingProcessId", daTrackingProcessId);
        vo.insertRow(row);
        this.getDBTransaction().commit();
    }

    //Insert DA Tracking Update
    public void insertDaTrackingUpdate(int daNumberId, int stepId, Timestamp date, int statusId, String comments) {
        ViewObject vo = this.getDaTrackingProcessView1();
        if (vo == null) {
            System.err.println("vo is NULL");
        }
        Row row = vo.createRow();
        row.setAttribute("DaId", daNumberId);
        row.setAttribute("DaStatusId", statusId);
        row.setAttribute("Comments", comments);
        row.setAttribute("StepId", stepId);
        row.setAttribute("DateEntered", date);
        vo.insertRow(row);
        this.getDBTransaction().commit();

    }

    /**Method to set file path and name * @param name * @param path */
    /*  public void setFileData(String documentName, String documentLocation, String description) {
        ViewObject fileVo = this.getDocumentsView1();
        ViewObject vo = getViewO
        if (vo == null) {
            System.err.println("vo is NULL");
        }
        if (fileVo == null) {
            System.err.println("fileVo is NULL");
        }
        Row newRow = fileVo.createRow();
        newRow.setAttribute("DocumentName", documentName);
        newRow.setAttribute("DocumentLocation", documentLocation);
        newRow.setAttribute("Description", description);
        fileVo.insertRow(newRow);
        this.getDBTransaction().commit();
        fileVo.executeQuery();
    }*/

    /**
     * Container's getter for DaStatuses1View1.
     * @return DaStatuses1View1
     */
    public ViewObjectImpl getDaStatuses1View1() {
        return (ViewObjectImpl) findViewObject("DaStatuses1View1");
    }

    /**
     * Container's getter for DaTrackingProcess1View1.
     * @return DaTrackingProcess1View1
     */
    public ViewObjectImpl getDaTrackingProcess1View1() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View1");
    }

    /**
     * Container's getter for DaTrackingProcessDocuments1View1.
     * @return DaTrackingProcessDocuments1View1
     */
    public ViewObjectImpl getDaTrackingProcessDocuments1View1() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcessDocuments1View1");
    }

    /**
     * Container's getter for DisbursementAuthorizations1View1.
     * @return DisbursementAuthorizations1View1
     */
    public DisbursementAuthorizations1ViewImpl getDisbursementAuthorizations1View1() {
        return (DisbursementAuthorizations1ViewImpl) findViewObject("DisbursementAuthorizations1View1");
    }

    /**
     * Container's getter for GroupMembersView1.
     * @return GroupMembersView1
     */
    public ViewObjectImpl getGroupMembersView1() {
        return (ViewObjectImpl) findViewObject("GroupMembersView1");
    }

    /**
     * Container's getter for Groups1View1.
     * @return Groups1View1
     */
    public ViewObjectImpl getGroups1View1() {
        return (ViewObjectImpl) findViewObject("Groups1View1");
    }

    /**
     * Container's getter for Steps1View1.
     * @return Steps1View1
     */
    public ViewObjectImpl getSteps1View1() {
        return (ViewObjectImpl) findViewObject("Steps1View1");
    }

    /**
     * Container's getter for Units1View1.
     * @return Units1View1
     */
    public ViewObjectImpl getUnits1View1() {
        return (ViewObjectImpl) findViewObject("Units1View1");
    }

    /**
     * Container's getter for Users1View1.
     * @return Users1View1
     */
    public ViewObjectImpl getUsers1View1() {
        return (ViewObjectImpl) findViewObject("Users1View1");
    }

    /**
     * Container's getter for DaTrackingProcess1View2.
     * @return DaTrackingProcess1View2
     */
    public ViewObjectImpl getDaTrackingProcess1View2() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View2");
    }

    /**
     * Container's getter for DaTrackingProcess1View3.
     * @return DaTrackingProcess1View3
     */
    public ViewObjectImpl getDaTrackingProcess1View3() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View3");
    }

    /**
     * Container's getter for DaTrackingProcess1View4.
     * @return DaTrackingProcess1View4
     */
    public ViewObjectImpl getDaTrackingProcess1View4() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View4");
    }

    /**
     * Container's getter for DaTrackingProcess1View5.
     * @return DaTrackingProcess1View5
     */
    public ViewObjectImpl getDaTrackingProcess1View5() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View5");
    }

    /**
     * Container's getter for DaTrackingProcess1View6.
     * @return DaTrackingProcess1View6
     */
    public ViewObjectImpl getDaTrackingProcess1View6() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View6");
    }

    /**
     * Container's getter for DaTrackingProcess1View7.
     * @return DaTrackingProcess1View7
     */
    public ViewObjectImpl getDaTrackingProcess1View7() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View7");
    }

    /**
     * Container's getter for DaTrackingProcess1View8.
     * @return DaTrackingProcess1View8
     */
    public ViewObjectImpl getDaTrackingProcess1View8() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View8");
    }

    /**
     * Container's getter for DaTrackingProcess1View9.
     * @return DaTrackingProcess1View9
     */
    public ViewObjectImpl getDaTrackingProcess1View9() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View9");
    }

    /**
     * Container's getter for DaTrackingProcessDocuments1View2.
     * @return DaTrackingProcessDocuments1View2
     */
    public ViewObjectImpl getDaTrackingProcessDocuments1View2() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcessDocuments1View2");
    }

    /**
     * Container's getter for DaTrackingProcess1View10.
     * @return DaTrackingProcess1View10
     */
    public ViewObjectImpl getDaTrackingProcess1View10() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View10");
    }

    /**
     * Container's getter for DaTrackingProcess1View11.
     * @return DaTrackingProcess1View11
     */
    public ViewObjectImpl getDaTrackingProcess1View11() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View11");
    }

    /**
     * Container's getter for DaTrackingProcess1View12.
     * @return DaTrackingProcess1View12
     */
    public ViewObjectImpl getDaTrackingProcess1View12() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View12");
    }

    /**
     * Container's getter for DaTrackingProcess1View13.
     * @return DaTrackingProcess1View13
     */
    public ViewObjectImpl getDaTrackingProcess1View13() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View13");
    }

    /**
     * Container's getter for DaTrackingProcessDocuments1View3.
     * @return DaTrackingProcessDocuments1View3
     */
    public ViewObjectImpl getDaTrackingProcessDocuments1View3() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcessDocuments1View3");
    }

    /**
     * Container's getter for DaTrackingProcessDocuments1View4.
     * @return DaTrackingProcessDocuments1View4
     */
    public ViewObjectImpl getDaTrackingProcessDocuments1View4() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcessDocuments1View4");
    }

    /**
     * Container's getter for DaTrackingProcessDocuments1View5.
     * @return DaTrackingProcessDocuments1View5
     */
    public ViewObjectImpl getDaTrackingProcessDocuments1View5() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcessDocuments1View5");
    }

    /**
     * Container's getter for DaTrackingProcess1View14.
     * @return DaTrackingProcess1View14
     */
    public ViewObjectImpl getDaTrackingProcess1View14() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View14");
    }

    /**
     * Container's getter for DaTrackingProcess1View15.
     * @return DaTrackingProcess1View15
     */
    public ViewObjectImpl getDaTrackingProcess1View15() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View15");
    }

    /**
     * Container's getter for DaTrackingProcess1View16.
     * @return DaTrackingProcess1View16
     */
    public ViewObjectImpl getDaTrackingProcess1View16() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View16");
    }

    /**
     * Container's getter for DaTrackingProcess1View17.
     * @return DaTrackingProcess1View17
     */
    public ViewObjectImpl getDaTrackingProcess1View17() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View17");
    }

    /**
     * Container's getter for DaTrackingProcessDocuments1View6.
     * @return DaTrackingProcessDocuments1View6
     */
    public ViewObjectImpl getDaTrackingProcessDocuments1View6() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcessDocuments1View6");
    }

    /**
     * Container's getter for DaTrackingProcess1View18.
     * @return DaTrackingProcess1View18
     */
    public ViewObjectImpl getDaTrackingProcess1View18() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View18");
    }

    /**
     * Container's getter for DaTrackingProcess1View19.
     * @return DaTrackingProcess1View19
     */
    public ViewObjectImpl getDaTrackingProcess1View19() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View19");
    }

    /**
     * Container's getter for DaTrackingProcess1View20.
     * @return DaTrackingProcess1View20
     */
    public ViewObjectImpl getDaTrackingProcess1View20() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View20");
    }

    /**
     * Container's getter for DaTrackingProcess1View21.
     * @return DaTrackingProcess1View21
     */
    public ViewObjectImpl getDaTrackingProcess1View21() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View21");
    }

    /**
     * Container's getter for DaTrackingProcessDocuments1View7.
     * @return DaTrackingProcessDocuments1View7
     */
    public ViewObjectImpl getDaTrackingProcessDocuments1View7() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcessDocuments1View7");
    }

    /**
     * Container's getter for DaTrackingProcess1View22.
     * @return DaTrackingProcess1View22
     */
    public ViewObjectImpl getDaTrackingProcess1View22() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View22");
    }

    /**
     * Container's getter for DaTrackingProcess1View23.
     * @return DaTrackingProcess1View23
     */
    public ViewObjectImpl getDaTrackingProcess1View23() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View23");
    }

    /**
     * Container's getter for DaTrackingProcess1View24.
     * @return DaTrackingProcess1View24
     */
    public ViewObjectImpl getDaTrackingProcess1View24() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View24");
    }

    /**
     * Container's getter for DaTrackingProcess1View25.
     * @return DaTrackingProcess1View25
     */
    public ViewObjectImpl getDaTrackingProcess1View25() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View25");
    }

    /**
     * Container's getter for DaTrackingProcessDocuments1View8.
     * @return DaTrackingProcessDocuments1View8
     */
    public ViewObjectImpl getDaTrackingProcessDocuments1View8() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcessDocuments1View8");
    }

    /**
     * Container's getter for DaTrackingProcess1View26.
     * @return DaTrackingProcess1View26
     */
    public ViewObjectImpl getDaTrackingProcess1View26() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View26");
    }

    /**
     * Container's getter for DaTrackingProcess1View27.
     * @return DaTrackingProcess1View27
     */
    public ViewObjectImpl getDaTrackingProcess1View27() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View27");
    }

    /**
     * Container's getter for DaTrackingProcess1View28.
     * @return DaTrackingProcess1View28
     */
    public ViewObjectImpl getDaTrackingProcess1View28() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View28");
    }

    /**
     * Container's getter for DaTrackingProcess1View29.
     * @return DaTrackingProcess1View29
     */
    public ViewObjectImpl getDaTrackingProcess1View29() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View29");
    }

    /**
     * Container's getter for DaTrackingProcessDocuments1View9.
     * @return DaTrackingProcessDocuments1View9
     */
    public ViewObjectImpl getDaTrackingProcessDocuments1View9() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcessDocuments1View9");
    }

    /**
     * Container's getter for DaTrackingProcess1View30.
     * @return DaTrackingProcess1View30
     */
    public ViewObjectImpl getDaTrackingProcess1View30() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View30");
    }

    /**
     * Container's getter for DaTrackingProcess1View31.
     * @return DaTrackingProcess1View31
     */
    public ViewObjectImpl getDaTrackingProcess1View31() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View31");
    }

    /**
     * Container's getter for DaTrackingProcess1View32.
     * @return DaTrackingProcess1View32
     */
    public ViewObjectImpl getDaTrackingProcess1View32() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View32");
    }

    /**
     * Container's getter for DaTrackingProcess1View33.
     * @return DaTrackingProcess1View33
     */
    public ViewObjectImpl getDaTrackingProcess1View33() {
        return (ViewObjectImpl) findViewObject("DaTrackingProcess1View33");
    }

    /**
     * Container's getter for Users1View2.
     * @return Users1View2
     */
    public ViewObjectImpl getUsers1View2() {
        return (ViewObjectImpl) findViewObject("Users1View2");
    }

    /**
     * Container's getter for Users1View3.
     * @return Users1View3
     */
    public ViewObjectImpl getUsers1View3() {
        return (ViewObjectImpl) findViewObject("Users1View3");
    }

    /**
     * Container's getter for Users1View4.
     * @return Users1View4
     */
    public ViewObjectImpl getUsers1View4() {
        return (ViewObjectImpl) findViewObject("Users1View4");
    }

    /**
     * Container's getter for Users1View5.
     * @return Users1View5
     */
    public ViewObjectImpl getUsers1View5() {
        return (ViewObjectImpl) findViewObject("Users1View5");
    }

    /**
     * Container's getter for Users1View6.
     * @return Users1View6
     */
    public ViewObjectImpl getUsers1View6() {
        return (ViewObjectImpl) findViewObject("Users1View6");
    }

    /**
     * Container's getter for Users1View7.
     * @return Users1View7
     */
    public ViewObjectImpl getUsers1View7() {
        return (ViewObjectImpl) findViewObject("Users1View7");
    }

    /**
     * Container's getter for Users1View8.
     * @return Users1View8
     */
    public ViewObjectImpl getUsers1View8() {
        return (ViewObjectImpl) findViewObject("Users1View8");
    }

    /**
     * Container's getter for Users1View9.
     * @return Users1View9
     */
    public ViewObjectImpl getUsers1View9() {
        return (ViewObjectImpl) findViewObject("Users1View9");
    }

    /**
     * Container's getter for Users1View10.
     * @return Users1View10
     */
    public ViewObjectImpl getUsers1View10() {
        return (ViewObjectImpl) findViewObject("Users1View10");
    }

    /**
     * Container's getter for Users1View11.
     * @return Users1View11
     */
    public ViewObjectImpl getUsers1View11() {
        return (ViewObjectImpl) findViewObject("Users1View11");
    }

    /**
     * Container's getter for Users1View12.
     * @return Users1View12
     */
    public ViewObjectImpl getUsers1View12() {
        return (ViewObjectImpl) findViewObject("Users1View12");
    }

    /**
     * Container's getter for Users1View13.
     * @return Users1View13
     */
    public ViewObjectImpl getUsers1View13() {
        return (ViewObjectImpl) findViewObject("Users1View13");
    }

    /**
     * Container's getter for Users1View14.
     * @return Users1View14
     */
    public ViewObjectImpl getUsers1View14() {
        return (ViewObjectImpl) findViewObject("Users1View14");
    }

    /**
     * Container's getter for Users1View15.
     * @return Users1View15
     */
    public ViewObjectImpl getUsers1View15() {
        return (ViewObjectImpl) findViewObject("Users1View15");
    }

    /**
     * Container's getter for Users1View16.
     * @return Users1View16
     */
    public ViewObjectImpl getUsers1View16() {
        return (ViewObjectImpl) findViewObject("Users1View16");
    }

    /**
     * Container's getter for Users1View17.
     * @return Users1View17
     */
    public ViewObjectImpl getUsers1View17() {
        return (ViewObjectImpl) findViewObject("Users1View17");
    }

    /**
     * Container's getter for FkDaTrackingProcessUsersAssoc8Link1.
     * @return FkDaTrackingProcessUsersAssoc8Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessUsersAssoc8Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessUsersAssoc8Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessStepsAssoc8Link1.
     * @return FkDaTrackingProcessStepsAssoc8Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessStepsAssoc8Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessStepsAssoc8Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDisbursementAuthoizationsAssoc8Link1.
     * @return FkDaTrackingProcessDisbursementAuthoizationsAssoc8Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDisbursementAuthoizationsAssoc8Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDisbursementAuthoizationsAssoc8Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDaStatusesAssoc8Link1.
     * @return FkDaTrackingProcessDaStatusesAssoc8Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDaStatusesAssoc8Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDaStatusesAssoc8Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDaStatusesAssoc9Link1.
     * @return FkDaTrackingProcessDaStatusesAssoc9Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDaStatusesAssoc9Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDaStatusesAssoc9Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDisbursementAuthoizationsAssoc9Link1.
     * @return FkDaTrackingProcessDisbursementAuthoizationsAssoc9Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDisbursementAuthoizationsAssoc9Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDisbursementAuthoizationsAssoc9Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessStepsAssoc9Link1.
     * @return FkDaTrackingProcessStepsAssoc9Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessStepsAssoc9Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessStepsAssoc9Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessUsersAssoc9Link1.
     * @return FkDaTrackingProcessUsersAssoc9Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessUsersAssoc9Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessUsersAssoc9Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDocumentsDaTrackingProcessAssoc8Link1.
     * @return FkDaTrackingProcessDocumentsDaTrackingProcessAssoc8Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDocumentsDaTrackingProcessAssoc8Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDocumentsDaTrackingProcessAssoc8Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessUsersAssoc10Link1.
     * @return FkDaTrackingProcessUsersAssoc10Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessUsersAssoc10Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessUsersAssoc10Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessStepsAssoc10Link1.
     * @return FkDaTrackingProcessStepsAssoc10Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessStepsAssoc10Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessStepsAssoc10Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDisbursementAuthoizationsAssoc10Link1.
     * @return FkDaTrackingProcessDisbursementAuthoizationsAssoc10Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDisbursementAuthoizationsAssoc10Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDisbursementAuthoizationsAssoc10Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDaStatusesAssoc10Link1.
     * @return FkDaTrackingProcessDaStatusesAssoc10Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDaStatusesAssoc10Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDaStatusesAssoc10Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDocumentsDaTrackingProcessAssoc9Link1.
     * @return FkDaTrackingProcessDocumentsDaTrackingProcessAssoc9Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDocumentsDaTrackingProcessAssoc9Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDocumentsDaTrackingProcessAssoc9Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDocumentsDaTrackingProcessAssoc10Link1.
     * @return FkDaTrackingProcessDocumentsDaTrackingProcessAssoc10Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDocumentsDaTrackingProcessAssoc10Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDocumentsDaTrackingProcessAssoc10Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDocumentsDaTrackingProcessAssoc11Link1.
     * @return FkDaTrackingProcessDocumentsDaTrackingProcessAssoc11Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDocumentsDaTrackingProcessAssoc11Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDocumentsDaTrackingProcessAssoc11Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessUsersAssoc11Link1.
     * @return FkDaTrackingProcessUsersAssoc11Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessUsersAssoc11Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessUsersAssoc11Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessStepsAssoc11Link1.
     * @return FkDaTrackingProcessStepsAssoc11Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessStepsAssoc11Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessStepsAssoc11Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDisbursementAuthoizationsAssoc11Link1.
     * @return FkDaTrackingProcessDisbursementAuthoizationsAssoc11Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDisbursementAuthoizationsAssoc11Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDisbursementAuthoizationsAssoc11Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDaStatusesAssoc11Link1.
     * @return FkDaTrackingProcessDaStatusesAssoc11Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDaStatusesAssoc11Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDaStatusesAssoc11Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDocumentsDaTrackingProcessAssoc12Link1.
     * @return FkDaTrackingProcessDocumentsDaTrackingProcessAssoc12Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDocumentsDaTrackingProcessAssoc12Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDocumentsDaTrackingProcessAssoc12Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessUsersAssoc12Link1.
     * @return FkDaTrackingProcessUsersAssoc12Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessUsersAssoc12Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessUsersAssoc12Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessStepsAssoc12Link1.
     * @return FkDaTrackingProcessStepsAssoc12Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessStepsAssoc12Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessStepsAssoc12Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDisbursementAuthoizationsAssoc12Link1.
     * @return FkDaTrackingProcessDisbursementAuthoizationsAssoc12Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDisbursementAuthoizationsAssoc12Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDisbursementAuthoizationsAssoc12Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDaStatusesAssoc12Link1.
     * @return FkDaTrackingProcessDaStatusesAssoc12Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDaStatusesAssoc12Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDaStatusesAssoc12Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDocumentsDaTrackingProcessAssoc13Link1.
     * @return FkDaTrackingProcessDocumentsDaTrackingProcessAssoc13Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDocumentsDaTrackingProcessAssoc13Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDocumentsDaTrackingProcessAssoc13Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessUsersAssoc13Link1.
     * @return FkDaTrackingProcessUsersAssoc13Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessUsersAssoc13Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessUsersAssoc13Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessStepsAssoc13Link1.
     * @return FkDaTrackingProcessStepsAssoc13Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessStepsAssoc13Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessStepsAssoc13Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDisbursementAuthoizationsAssoc13Link1.
     * @return FkDaTrackingProcessDisbursementAuthoizationsAssoc13Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDisbursementAuthoizationsAssoc13Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDisbursementAuthoizationsAssoc13Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDaStatusesAssoc13Link1.
     * @return FkDaTrackingProcessDaStatusesAssoc13Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDaStatusesAssoc13Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDaStatusesAssoc13Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDocumentsDaTrackingProcessAssoc14Link1.
     * @return FkDaTrackingProcessDocumentsDaTrackingProcessAssoc14Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDocumentsDaTrackingProcessAssoc14Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDocumentsDaTrackingProcessAssoc14Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessUsersAssoc14Link1.
     * @return FkDaTrackingProcessUsersAssoc14Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessUsersAssoc14Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessUsersAssoc14Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessStepsAssoc14Link1.
     * @return FkDaTrackingProcessStepsAssoc14Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessStepsAssoc14Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessStepsAssoc14Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDisbursementAuthoizationsAssoc14Link1.
     * @return FkDaTrackingProcessDisbursementAuthoizationsAssoc14Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDisbursementAuthoizationsAssoc14Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDisbursementAuthoizationsAssoc14Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDaStatusesAssoc14Link1.
     * @return FkDaTrackingProcessDaStatusesAssoc14Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDaStatusesAssoc14Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDaStatusesAssoc14Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDocumentsDaTrackingProcessAssoc15Link1.
     * @return FkDaTrackingProcessDocumentsDaTrackingProcessAssoc15Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDocumentsDaTrackingProcessAssoc15Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDocumentsDaTrackingProcessAssoc15Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessUsersAssoc15Link1.
     * @return FkDaTrackingProcessUsersAssoc15Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessUsersAssoc15Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessUsersAssoc15Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessStepsAssoc15Link1.
     * @return FkDaTrackingProcessStepsAssoc15Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessStepsAssoc15Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessStepsAssoc15Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDisbursementAuthoizationsAssoc15Link1.
     * @return FkDaTrackingProcessDisbursementAuthoizationsAssoc15Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDisbursementAuthoizationsAssoc15Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDisbursementAuthoizationsAssoc15Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDaStatusesAssoc15Link1.
     * @return FkDaTrackingProcessDaStatusesAssoc15Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDaStatusesAssoc15Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDaStatusesAssoc15Link1");
    }

    /**
     * Container's getter for FkUsersGroupsAssoc8Link1.
     * @return FkUsersGroupsAssoc8Link1
     */
    public ViewLinkImpl getFkUsersGroupsAssoc8Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersGroupsAssoc8Link1");
    }

    /**
     * Container's getter for FkUsersGroupsAssoc9Link1.
     * @return FkUsersGroupsAssoc9Link1
     */
    public ViewLinkImpl getFkUsersGroupsAssoc9Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersGroupsAssoc9Link1");
    }

    /**
     * Container's getter for FkUsersGroupsAssoc10Link1.
     * @return FkUsersGroupsAssoc10Link1
     */
    public ViewLinkImpl getFkUsersGroupsAssoc10Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersGroupsAssoc10Link1");
    }

    /**
     * Container's getter for FkUsersGroupsAssoc11Link1.
     * @return FkUsersGroupsAssoc11Link1
     */
    public ViewLinkImpl getFkUsersGroupsAssoc11Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersGroupsAssoc11Link1");
    }

    /**
     * Container's getter for FkUsersGroupsAssoc12Link1.
     * @return FkUsersGroupsAssoc12Link1
     */
    public ViewLinkImpl getFkUsersGroupsAssoc12Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersGroupsAssoc12Link1");
    }

    /**
     * Container's getter for FkUsersGroupsAssoc13Link1.
     * @return FkUsersGroupsAssoc13Link1
     */
    public ViewLinkImpl getFkUsersGroupsAssoc13Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersGroupsAssoc13Link1");
    }

    /**
     * Container's getter for FkUsersGroupsAssoc14Link1.
     * @return FkUsersGroupsAssoc14Link1
     */
    public ViewLinkImpl getFkUsersGroupsAssoc14Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersGroupsAssoc14Link1");
    }

    /**
     * Container's getter for FkUsersGroupsAssoc15Link1.
     * @return FkUsersGroupsAssoc15Link1
     */
    public ViewLinkImpl getFkUsersGroupsAssoc15Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersGroupsAssoc15Link1");
    }

    /**
     * Container's getter for FkUsersUnitsAssoc8Link1.
     * @return FkUsersUnitsAssoc8Link1
     */
    public ViewLinkImpl getFkUsersUnitsAssoc8Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersUnitsAssoc8Link1");
    }

    /**
     * Container's getter for FkUsersUnitsAssoc9Link1.
     * @return FkUsersUnitsAssoc9Link1
     */
    public ViewLinkImpl getFkUsersUnitsAssoc9Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersUnitsAssoc9Link1");
    }

    /**
     * Container's getter for FkUsersUnitsAssoc10Link1.
     * @return FkUsersUnitsAssoc10Link1
     */
    public ViewLinkImpl getFkUsersUnitsAssoc10Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersUnitsAssoc10Link1");
    }

    /**
     * Container's getter for FkUsersUnitsAssoc11Link1.
     * @return FkUsersUnitsAssoc11Link1
     */
    public ViewLinkImpl getFkUsersUnitsAssoc11Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersUnitsAssoc11Link1");
    }

    /**
     * Container's getter for FkUsersUnitsAssoc12Link1.
     * @return FkUsersUnitsAssoc12Link1
     */
    public ViewLinkImpl getFkUsersUnitsAssoc12Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersUnitsAssoc12Link1");
    }

    /**
     * Container's getter for FkUsersUnitsAssoc13Link1.
     * @return FkUsersUnitsAssoc13Link1
     */
    public ViewLinkImpl getFkUsersUnitsAssoc13Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersUnitsAssoc13Link1");
    }

    /**
     * Container's getter for FkUsersUnitsAssoc14Link1.
     * @return FkUsersUnitsAssoc14Link1
     */
    public ViewLinkImpl getFkUsersUnitsAssoc14Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersUnitsAssoc14Link1");
    }

    /**
     * Container's getter for FkUsersUnitsAssoc15Link1.
     * @return FkUsersUnitsAssoc15Link1
     */
    public ViewLinkImpl getFkUsersUnitsAssoc15Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersUnitsAssoc15Link1");
    }

    /**
     * Container's getter for DaTrackingProcessDocumentsView2.
     * @return DaTrackingProcessDocumentsView2
     */
    public DaTrackingProcessDocumentsViewImpl getDaTrackingProcessDocumentsView2() {
        return (DaTrackingProcessDocumentsViewImpl) findViewObject("DaTrackingProcessDocumentsView2");
    }

    /**
     * Container's getter for DaTrackingProcessView18.
     * @return DaTrackingProcessView18
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView18() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView18");
    }

    /**
     * Container's getter for DaTrackingProcessView19.
     * @return DaTrackingProcessView19
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView19() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView19");
    }

    /**
     * Container's getter for DaTrackingProcessView20.
     * @return DaTrackingProcessView20
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView20() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView20");
    }

    /**
     * Container's getter for DaTrackingProcessView21.
     * @return DaTrackingProcessView21
     */
    public DaTrackingProcessViewImpl getDaTrackingProcessView21() {
        return (DaTrackingProcessViewImpl) findViewObject("DaTrackingProcessView21");
    }

    /**
     * Container's getter for DaTrackingProcessDocumentsView6.
     * @return DaTrackingProcessDocumentsView6
     */
    public DaTrackingProcessDocumentsViewImpl getDaTrackingProcessDocumentsView6() {
        return (DaTrackingProcessDocumentsViewImpl) findViewObject("DaTrackingProcessDocumentsView6");
    }

    /**
     * Container's getter for DaTrackingProcessDocumentsView7.
     * @return DaTrackingProcessDocumentsView7
     */
    public DaTrackingProcessDocumentsViewImpl getDaTrackingProcessDocumentsView7() {
        return (DaTrackingProcessDocumentsViewImpl) findViewObject("DaTrackingProcessDocumentsView7");
    }

    /**
     * Container's getter for DaTrackingProcessDocumentsView8.
     * @return DaTrackingProcessDocumentsView8
     */
    public DaTrackingProcessDocumentsViewImpl getDaTrackingProcessDocumentsView8() {
        return (DaTrackingProcessDocumentsViewImpl) findViewObject("DaTrackingProcessDocumentsView8");
    }

    /**
     * Container's getter for UsersView2.
     * @return UsersView2
     */
    public UsersViewImpl getUsersView2() {
        return (UsersViewImpl) findViewObject("UsersView2");
    }

    /**
     * Container's getter for UsersView10.
     * @return UsersView10
     */
    public UsersViewImpl getUsersView10() {
        return (UsersViewImpl) findViewObject("UsersView10");
    }

    /**
     * Container's getter for FkDaTrackingProcessUsersAssoc4Link1.
     * @return FkDaTrackingProcessUsersAssoc4Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessUsersAssoc4Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessUsersAssoc4Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessStepsAssoc4Link1.
     * @return FkDaTrackingProcessStepsAssoc4Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessStepsAssoc4Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessStepsAssoc4Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDisbursementAuthoizationsAssoc4Link1.
     * @return FkDaTrackingProcessDisbursementAuthoizationsAssoc4Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDisbursementAuthoizationsAssoc4Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDisbursementAuthoizationsAssoc4Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDaStatusesAssoc4Link1.
     * @return FkDaTrackingProcessDaStatusesAssoc4Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDaStatusesAssoc4Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDaStatusesAssoc4Link1");
    }

    /**
     * Container's getter for FkDaTrackingProcessDocumentsDaTrackingProcessAssoc4Link1.
     * @return FkDaTrackingProcessDocumentsDaTrackingProcessAssoc4Link1
     */
    public ViewLinkImpl getFkDaTrackingProcessDocumentsDaTrackingProcessAssoc4Link1() {
        return (ViewLinkImpl) findViewLink("FkDaTrackingProcessDocumentsDaTrackingProcessAssoc4Link1");
    }

    /**
     * Container's getter for FkUsersGroupsLink1.
     * @return FkUsersGroupsLink1
     */
    public ViewLinkImpl getFkUsersGroupsLink1() {
        return (ViewLinkImpl) findViewLink("FkUsersGroupsLink1");
    }

    /**
     * Container's getter for FkUsersUnitsLink1.
     * @return FkUsersUnitsLink1
     */
    public ViewLinkImpl getFkUsersUnitsLink1() {
        return (ViewLinkImpl) findViewLink("FkUsersUnitsLink1");
    }

    /**
     * Container's getter for DistrictsView1.
     * @return DistrictsView1
     */
    public DistrictsViewImpl getDistrictsView1() {
        return (DistrictsViewImpl) findViewObject("DistrictsView1");
    }

    public boolean updateStep1(String daNumber, String comments) {
        boolean isSuccessful = false;
        try {
            ViewObjectImpl vo = getDisbursementAuthorizationsView1();
            Row row = vo.createRow();
            row.setAttribute("DaNumber", daNumber);
            row.setAttribute("Description", comments);
            this.getDBTransaction().commit();
            vo.executeQuery();
            isSuccessful = true;
        } catch (Exception exception) {
            exception.printStackTrace();
        }
        return isSuccessful;
    }

    public boolean updateStep2(String oldDaNumber, String newDaNumber,float totalValue, int numberOfBeneficiaries, int districtId, String comments, int userId, int daId) {
        boolean isSuccessful = false;
        String da ="";
       try {
            ViewObjectImpl vo = getDisbursementAuthorizationsView1();
            Row row;
            while (vo.getRowSet().hasNext()) {
                row = vo.next();
                //oldDaNumber = row.getAttribute("DaNumber")==null ? "" : row.getAttribute("DaNumber").toString();
                if (row.getAttribute("DaNumber") != null) {
                    da = row.getAttribute("DaNumber").toString();
                   // if (oldDaNumber == row.getAttribute("DaNumber").toString()) {
                   if (daId == Integer.parseInt(row.getAttribute("Id").toString())) {
                        //Update row values
                        row.setAttribute("DaNumber", newDaNumber);
                        row.setAttribute("NumberOfBeneficiaries", numberOfBeneficiaries);
                        row.setAttribute("TotalValue", totalValue);
                        if(districtId==0){
                            districtId = 1;
                        }
                        row.setAttribute("DistrictId", districtId);                        
                    }
                }
            }
            this.getDBTransaction().commit();
            vo.executeQuery();
            isSuccessful = true;
            // Call insertDAProgress
         //    insertDAProgress(2,  userId,  daId,  comments);
           
           //Send email
         //  SendEmail sendEmail = new SendEmail();
         //  SendEmail.send("vouchertracker@gmail.com", "chemweno@gmail.com", "Voucher Tracker Activity", "");
        } catch (Exception exception) {
            exception.printStackTrace();
        }
        return isSuccessful;
    }
    
  //Email will be sent to vouchertracker@gmail.com and BCC sent to responsible users for the particular step.
  // public void i(int stepId, String daNumber){
  public void sendEmailNotification(int stepId){
        try{
            UsersViewImpl usersViewImpl = new UsersViewImpl();
            Map<String, String> emailsList = getStepResponsibleUsersEmails(stepId);
            //My first ever ever lambda expression. Welcome to Java 8
            emailsList.forEach((userFirstname,email)->{
                SendEmail.send("vouchertracker@gmail.com", "", email,"Voucher Tracker Activity", "Dear "+userFirstname+", \r\n" +
                         //"Your attention is drawn to an update made to DA Number '"+daNumber+ "'. \"\\r\\n\"" +
                         "\r\n"    +   
                         "Your attention is drawn to an update made on Voucher Tracker System. \r\n" +
                         "For more details, log on to Voucher Tracker system. \r\n" +
                         "\r\n"    +                
                           "Regards \r\n" +
                         "**This is a system generated email DO NOT REPLY **");
                System.out.println("Email sent to "+userFirstname+ " at "+ new Date());
            });                         
        }catch(Exception exception){
            System.err.println("Error sending email notification");
            exception.printStackTrace();
        }
    } 
  
    public void sendEmailNotification(int stepId, String daNumber, String loggedInUserFullname, String comments){
        try{
              Map<String, String> emailsList = getStepResponsibleUsersEmails(stepId);
             emailsList.forEach((userFirstname,email)->{
                 //email = "kiprotich.chemweno@fao.org";
                 dats.model.SendEmail.send("vouchertracker@gmail.com", "", email,"Voucher Tracker Activity", "Dear "+userFirstname+", \r\n" +
                          "\r\n" +
                          "Your attention is drawn to an update made to DA Number '"+daNumber+ "'. \r\n" +
                          " by '"+loggedInUserFullname+"' with the following comments; " +
                          "\r\n" +                                                                                   
                          "'"+comments+"'"  +    
                          "\r\n" +                                                                                                             
                          "For more details, log on to Voucher Tracker system. \r\n" +
                           "http://dats.faoso.net/dats/faces/login.jsf" +                                                                                                           
                          "\r\n" +
                          "Regards \r\n" +
                          "**This is a system egenerated email DO NOT REPLY **");
                 System.out.println("Email sent to "+userFirstname+ " at "+ new Date());
             });                      
          }catch(Exception exception){
              System.err.println("Error sending email notification");
              exception.printStackTrace();
          }
      }   
    
    public void sendEmailNotificationGenerateDaNumber(int stepId, String daNumber, String loggedInUserFullname, String comments){
        try{
              Map<String, String> emailsList = getStepResponsibleUsersEmails(stepId);
             emailsList.forEach((userFirstname,email)->{
                 //email = "kiprotich.chemweno@fao.org";
                 dats.model.SendEmail.send("vouchertracker@gmail.com", "", email,"Voucher Tracker Activity", "Dear "+userFirstname+", \r\n" +
                          "\r\n" +
                          "New DA Number '"+daNumber+ "' has been created. \r\n" +
                          " by '"+loggedInUserFullname+"' with the following comments; " +
                          "\r\n" +                                                                                   
                          "'"+comments+"'"  +    
                          "\r\n" +                                                                                                             
                          "For more details, log on to Voucher Tracker system. \r\n" +
                           "http://dats.faoso.net/dats/faces/login.jsf" +                                                                                                           
                          "\r\n" +
                          "Regards \r\n" +
                          "**This is a system egenerated email DO NOT REPLY **");
                 System.out.println("Email sent to "+userFirstname+ " at "+ new Date());
             });                      
          }catch(Exception exception){
              System.err.println("Error sending email notification");
             // exception.printStackTrace();
          }
      }  
    
    /*
    public boolean updateStep2New(String oldDaNumber, String newDaNumber,float totalValue, int numberOfBeneficiaries, int districtId, String comments, int userId, int daId) {
        boolean isSuccessful = false;
        String da ="";
       try {
            ViewObjectImpl vo = getDisbursementAuthorizationsView1();
            Row row;
            while (vo.getRowSet().hasNext()) {
                row = vo.next();
                //oldDaNumber = row.getAttribute("DaNumber")==null ? "" : row.getAttribute("DaNumber").toString();
                if (row.getAttribute("DaNumber") != null) {
                    da = row.getAttribute("DaNumber").toString();
                   // if (oldDaNumber == row.getAttribute("DaNumber").toString()) {
                   if (daId == Integer.parseInt(row.getAttribute("Id").toString())) {
                        //Update row values
                        row.setAttribute("DaNumber", newDaNumber);
                        row.setAttribute("NumberOfBeneficiaries", numberOfBeneficiaries);
                        row.setAttribute("TotalValue", totalValue);
                        if(districtId==0){
                            districtId = 1;
                        }
                        row.setAttribute("DistrictId", districtId);                        
                    }
                }
            }
            this.getDBTransaction().commit();
            vo.executeQuery();
            isSuccessful = true;
            // Call insertDAProgress
             insertDAProgress(2,  userId,  daId,  comments);
        } catch (Exception exception) {
            exception.printStackTrace();
        }
        return isSuccessful;
    }    */
    
    public boolean updateStep2Details(String oldDaNumber, String newDaNumber,float totalValue, int numberOfBeneficiaries, int districtId, String comments, int userId, int daId) {
        boolean isSuccessful = false;
      /* try {
            ViewObjectImpl vo = getDisbursementAuthorizationsView1();
            Row row;
            while (vo.getRowSet().hasNext()) {
                row = vo.next();
                //oldDaNumber = row.getAttribute("DaNumber")==null ? "" : row.getAttribute("DaNumber").toString();
                if (row.getAttribute("DaNumber") != null) {
                    if (oldDaNumber == row.getAttribute("DaNumber").toString()) {
                        //Update row values
                        row.setAttribute("DaNumber", newDaNumber);
                        row.setAttribute("NumberOfBeneficiaries", numberOfBeneficiaries);
                        row.setAttribute("TotalValue", totalValue);
                        row.setAttribute("DistrictId", districtId);                        
                    }
                }
            }
            this.getDBTransaction().commit();
            vo.executeQuery();
            isSuccessful = true;
            // Call insertDAProgress
//             insertDAProgress( 2,  userId,  daId,  comments);
        } catch (Exception exception) {
            exception.printStackTrace();
        }*/
        return isSuccessful;
    }    

    //public boolean insertDAProgressDetails(int stepId, int userId, int daId, String comments) {
    //public boolean insertDaDetails(int stepId, int userId, int daId, String comments) {
    //public boolean insertDaStepProgressDetails(int stepId, int userId, int daId, String comments) {
    public boolean insertDaStepDetailsProgress(int stepId, int userId, String loggedInUserFullname,int daId, String comments) {       
        boolean isSuccessful = false;
        setInsertDaStepIsSuccessful(isSuccessful);
        ApplicationModule appMod = Configuration.createRootApplicationModule("dats.model.AppModule", "AppModuleLocal");
       // StepResponsiblePersonsViewImpl vo = (StepResponsiblePersonsViewImpl) appMod.findViewObject("DaTrackingProcessView1");            
        try {
            DisbursementAuthorizations1ViewImpl disbursementAuthorizationsViewImpl = new DisbursementAuthorizations1ViewImpl();
          //  ViewObjectImpl vo = getDaTrackingProcessView1();
            DaTrackingProcessViewImpl vo = (DaTrackingProcessViewImpl) appMod.findViewObject("DaTrackingProcessView1");         
            Row row = vo.createRow();
            row.setAttribute("DaId", daId);
            row.setAttribute("UserId", userId);
            row.setAttribute("StepId", stepId);
            row.setAttribute("Comments", comments);                              
            //this.getDBTransaction().commit();
            vo.getDBTransaction().commit();
            vo.executeQuery();
            sendEmailNotification(stepId, disbursementAuthorizationsViewImpl.getDaNumber(daId), loggedInUserFullname, comments);
            //sendEmailNotification(stepId);
            isSuccessful = true;
            setInsertDaStepIsSuccessful(isSuccessful);
        
        } catch (Exception exception) {
            setInsertDaStepIsSuccessful(false);
            System.err.println("Error encountered inserting DA Progress");
           // exception.printStackTrace();           
        }finally{
            if(appMod != null){
                Configuration.releaseRootApplicationModule(appMod, false);                      
            }            
        }
        return isSuccessful;
    }   
   /* 
    private void showMessageSuccess() {
        FacesMessage Message = new FacesMessage("File Upload Successful!");
        Message.setSeverity(FacesMessage.SEVERITY_INFO);
        FacesContext fc = FacesContext.getCurrentInstance();
        fc.addMessage(null, Message);
    }  */  
    
    //Create an arraylist of user emails for users responsible for the step provided
    //The method gets userids responsible for a step then uses the userids to get email addresses
    public Map<String, String> getStepResponsibleUsersEmails(int stepId){
        Map<String, String> userEmails = new HashMap<>();
        ApplicationModule appMod=null;
        StepResponsiblePersonsViewImpl vo;
        try{   
           appMod = Configuration.createRootApplicationModule("dats.model.AppModule", "AppModuleLocal");
            vo = (StepResponsiblePersonsViewImpl) appMod.findViewObject("StepResponsiblePersonsView1");         
            UsersViewImpl usersViewImpl = new UsersViewImpl();
            //Create View criteria
            ViewCriteria viewCriteria = vo.createViewCriteria();
            ViewCriteriaRow viewCriteriaRow = viewCriteria.createViewCriteriaRow();
            viewCriteriaRow.setAttribute("StepId", stepId);
            viewCriteria.add(viewCriteriaRow);
            viewCriteria.setCriteriaMode(ViewCriteria.CRITERIA_MODE_CACHE);
            vo.applyViewCriteria(viewCriteria);
            vo.executeQuery();            
            while (vo.hasNext()) {
                StepResponsiblePersonsViewRowImpl row = (StepResponsiblePersonsViewRowImpl) vo.next();
                userEmails.put( usersViewImpl.getUserFirstName(row.getUserId()) , usersViewImpl.getEmail(row.getUserId()+""));
            }                       
        }catch(Exception exception){
            System.err.println("Error encountered when getting emails for users responsible for various steps");
           // exception.printStackTrace();
        }finally{
            if(appMod != null){
                Configuration.releaseRootApplicationModule(appMod, false);                      
            }            
            vo = null;
        }
        return userEmails;
    }    
   
    /*Generate DA Number and DA number details*/ 
    //public boolean insertGenerateDA(float totalValue, int beneficiariesNumber, int districtId, int ngoId, int interventionTypeId, String daNumber, String loaNumber, String phase,  String comments) {
    public boolean insertGenerateDaDetails(float totalValue, int beneficiariesNumber, int districtId, int ngoId, int interventionTypeId, int phaseId, String daNumber, String loaNumber, String comments, String loggedInUserFullname, int userId) {
    //public boolean insertGenerateDaValues(float totalValue, int beneficiariesNumber, int districtId, int ngoId, int interventionTypeId, String daNumber, String loaNumber, int phaseId,  String comments) {
    DisbursementAuthorizations1ViewImpl disbursementAuthorizationsViewImpl = new DisbursementAuthorizations1ViewImpl();
        boolean isSuccessful = false;
        ApplicationModule appMod = null;
        try {
            //ViewObjectImpl vo = getDisbursementAuthorizations1View1();
            appMod = Configuration.createRootApplicationModule("dats.model.AppModule", "AppModuleShared");
            DisbursementAuthorizations1ViewImpl vo = (DisbursementAuthorizations1ViewImpl) appMod.findViewObject("DisbursementAuthorizations1View1");                
            Row row = vo.createRow();
            row.setAttribute("DaNumber", daNumber);
            row.setAttribute("TotalValue", totalValue);
            row.setAttribute("NumberOfBeneficiaries", beneficiariesNumber);
            row.setAttribute("Description", comments);            
            row.setAttribute("DistrictId", districtId);
            row.setAttribute("LoaNumber", loaNumber);
            row.setAttribute("NgoId", ngoId);
            row.setAttribute("PhaseId", phaseId);  
            row.setAttribute("InterventionTypeId", interventionTypeId);     
         //   this.getDBTransaction().commit();       
            appMod.getTransaction().commit();
            vo.executeQuery();
            isSuccessful = true;
           // setInsertDaStepIsSuccessful(true);
            //Update da process progress           
           insertDaStepDetails(2, userId, loggedInUserFullname, disbursementAuthorizationsViewImpl.getDAId(daNumber), comments);            
           sendEmailNotificationGenerateDaNumber(2, daNumber, loggedInUserFullname, comments);
        } catch (Exception exception) {
            System.err.println("Error Generating DA Number");
        }finally{
            if(appMod != null){
                Configuration.releaseRootApplicationModule(appMod, false);                      
            }            
        }
        return isSuccessful;
    }        
    
    
    public boolean insertDaStepDetails(int stepId, int userId, String loggedInUserFullname,int daId, String comments) {       
        boolean isSuccessful = false;
        setInsertDaStepIsSuccessful(isSuccessful);
        ApplicationModule appMod = Configuration.createRootApplicationModule("dats.model.AppModule", "AppModuleLocal");
            //StepResponsiblePersonsViewImpl vo = (StepResponsiblePersonsViewImpl) appMod.findViewObject("DaTrackingProcessView1");            
        try {
            DisbursementAuthorizations1ViewImpl disbursementAuthorizationsViewImpl = new DisbursementAuthorizations1ViewImpl();
            //ViewObjectImpl vo = getDaTrackingProcessView1();
            DaTrackingProcessViewImpl vo = (DaTrackingProcessViewImpl) appMod.findViewObject("DaTrackingProcessView1");         
            Row row = vo.createRow();
            row.setAttribute("DaId", daId);
            row.setAttribute("UserId", userId);
            row.setAttribute("StepId", stepId);
            row.setAttribute("Comments", comments);                              
            //this.getDBTransaction().commit();
            appMod.getTransaction().commit();
            vo.executeQuery();
            //sendEmailNotification(stepId, disbursementAuthorizationsViewImpl.getDaNumber(daId), loggedInUserFullname, comments);
            //sendEmailNotification(stepId);
            isSuccessful = true;
            setInsertDaStepIsSuccessful(isSuccessful);
        
        } catch (Exception exception) {
            setInsertDaStepIsSuccessful(false);
            System.err.println("Error encountered inserting DA Progress");
            appMod=null;
           // exception.printStackTrace();           
        }
        return isSuccessful;
    }    

    public void setInsertDaStepIsSuccessful(boolean insertDaStepIsSuccessful) {
        this.insertDaStepIsSuccessful = insertDaStepIsSuccessful;
    }

    public boolean isInsertDaStepIsSuccessful() {
        return this.insertDaStepIsSuccessful;
    }

    /**Method to set file path, file name, step id and da id * @param name * @param path */
    public boolean insertRequestDaFileDetails(int stepId, int daId, String documentName, String documentLocation, String description) {
        //ApplicationModule appMod = Configuration.createRootApplicationModule("dats.model.AppModule", "AppModuleLocal");
        boolean isSuccessful = false;
        try{
        ViewObjectImpl vo = getDaTrackingProcessDocumentsView1();
       //DaTrackingProcessDocumentsViewImpl  fileVo = (DaTrackingProcessDocumentsViewImpl) appMod.findViewObject("DaTrackingProcessDocumentsView1");
        Row row = vo.createRow();
        //newRow.setAttribute("DaTrackingProcessId", daTrackingProcessId);
        row.setAttribute("StepId", stepId);    
        row.setAttribute("DaId", daId);   
        row.setAttribute("DocumentName", documentName);
        row.setAttribute("DocumentLocation", documentLocation);
        row.setAttribute("Description", description);
        vo.insertRow(row);
        vo.getDBTransaction().commit();
        isSuccessful = true;
        vo.executeQuery();
        }catch(Exception exception){
            System.err.println("Error inserting request DA file ");
            isSuccessful = false;
            //exception.printStackTrace();
        }
        return isSuccessful;
   // }    
    }    

    /**
     * Container's getter for InterventionTypesView1.
     * @return InterventionTypesView1
     */
    public ViewObjectImpl getInterventionTypesView1() {
        return (ViewObjectImpl) findViewObject("InterventionTypesView1");
    }

    /**
     * Container's getter for NgosView1.
     * @return NgosView1
     */
    public ViewObjectImpl getNgosView1() {
        return (ViewObjectImpl) findViewObject("NgosView1");
    }

    /**
     * Container's getter for StepResponsiblePersonsView1.
     * @return StepResponsiblePersonsView1
     */
    public StepResponsiblePersonsViewImpl getStepResponsiblePersonsView1() {
        return (StepResponsiblePersonsViewImpl) findViewObject("StepResponsiblePersonsView1");
    }

    /**
     * Container's getter for PhasesView1.
     * @return PhasesView1
     */
    public ViewObjectImpl getPhasesView1() {
        return (ViewObjectImpl) findViewObject("PhasesView1");
    }

    /**
     * Container's getter for DisbursementAuthorizations1View2.
     * @return DisbursementAuthorizations1View2
     */
    public DisbursementAuthorizations1ViewImpl getDisbursementAuthorizations1View2() {
        return (DisbursementAuthorizations1ViewImpl) findViewObject("DisbursementAuthorizations1View2");
    }

    /**
     * Container's getter for DisbursementAuthorizations1View3.
     * @return DisbursementAuthorizations1View3
     */
    public DisbursementAuthorizations1ViewImpl getDisbursementAuthorizations1View3() {
        return (DisbursementAuthorizations1ViewImpl) findViewObject("DisbursementAuthorizations1View3");
    }

    /**
     * Container's getter for DisbursementAuthorizations1View4.
     * @return DisbursementAuthorizations1View4
     */
    public DisbursementAuthorizations1ViewImpl getDisbursementAuthorizations1View4() {
        return (DisbursementAuthorizations1ViewImpl) findViewObject("DisbursementAuthorizations1View4");
    }

    /**
     * Container's getter for FkDisbursementAuthorizationsNgosLink1.
     * @return FkDisbursementAuthorizationsNgosLink1
     */
    public ViewLinkImpl getFkDisbursementAuthorizationsNgosLink1() {
        return (ViewLinkImpl) findViewLink("FkDisbursementAuthorizationsNgosLink1");
    }

    /**
     * Container's getter for FkDisbursementAuthorizationsInterventionTypesLink1.
     * @return FkDisbursementAuthorizationsInterventionTypesLink1
     */
    public ViewLinkImpl getFkDisbursementAuthorizationsInterventionTypesLink1() {
        return (ViewLinkImpl) findViewLink("FkDisbursementAuthorizationsInterventionTypesLink1");
    }

    /**
     * Container's getter for FkDisbursementAuthorizationsDistrictsLink1.
     * @return FkDisbursementAuthorizationsDistrictsLink1
     */
    public ViewLinkImpl getFkDisbursementAuthorizationsDistrictsLink1() {
        return (ViewLinkImpl) findViewLink("FkDisbursementAuthorizationsDistrictsLink1");
    }

    /**
     * Container's getter for CategoriesView1.
     * @return CategoriesView1
     */
    public ViewObjectImpl getCategoriesView1() {
        return (ViewObjectImpl) findViewObject("CategoriesView1");
    }

    /**
     * Container's getter for DistributedItemsView1.
     * @return DistributedItemsView1
     */
    public ViewObjectImpl getDistributedItemsView1() {
        return (ViewObjectImpl) findViewObject("DistributedItemsView1");
    }

    /**
     * Container's getter for PaymentCyclesView1.
     * @return PaymentCyclesView1
     */
    public ViewObjectImpl getPaymentCyclesView1() {
        return (ViewObjectImpl) findViewObject("PaymentCyclesView1");
    }

    /**
     * Container's getter for PaymentsView1.
     * @return PaymentsView1
     */
    public PaymentsViewImpl getPaymentsView1() {
        return (PaymentsViewImpl) findViewObject("PaymentsView1");
    }

    /**
     * Container's getter for RatesView1.
     * @return RatesView1
     */
    public RatesViewImpl getRatesView1() {
        return (RatesViewImpl) findViewObject("RatesView1");
    }

    /**
     * Container's getter for SectorsView1.
     * @return SectorsView1
     */
    public ViewObjectImpl getSectorsView1() {
        return (ViewObjectImpl) findViewObject("SectorsView1");
    }

    /**
     * Container's getter for MoneyVendorsView1.
     * @return MoneyVendorsView1
     */
    public ViewObjectImpl getMoneyVendorsView1() {
        return (ViewObjectImpl) findViewObject("MoneyVendorsView1");
    }

    /**
     * Container's getter for LoasView1.
     * @return LoasView1
     */
    public ViewObjectImpl getLoasView1() {
        return (ViewObjectImpl) findViewObject("LoasView1");
    }

    /**
     * Container's getter for PaymentLocationsView1.
     * @return PaymentLocationsView1
     */
    public ViewObjectImpl getPaymentLocationsView1() {
        return (ViewObjectImpl) findViewObject("PaymentLocationsView1");
    }
    
    //Get rateValue for rateId
   /* public float getRateValue(int rateId) {
        float rateValue = 0;
        return rateValue;
    }  */

    /**
     * Container's getter for LoginUsersView1.
     * @return LoginUsersView1
     */
    public LoginUsersViewImpl getLoginUsersView1() {
        return (LoginUsersViewImpl) findViewObject("LoginUsersView1");
    }
}

