package dats.model;

import oracle.jbo.ApplicationModule;
import oracle.jbo.Row;
import oracle.jbo.client.Configuration;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 12 18:22:13 EAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DaTrackingProcessDocumentsViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DaTrackingProcessDocumentsViewImpl() {
    }
    
    /**Method to set file path and name * @param name * @param path */
    public void setFileData(int daTrackingProcessId, String documentName, String documentLocation, String description) {
       ApplicationModule appMod = null; 
       DaTrackingProcessDocumentsViewImpl  fileVo = null;
       try{
        appMod = Configuration.createRootApplicationModule("dats.model.AppModule", "AppModuleLocal");
        fileVo = (DaTrackingProcessDocumentsViewImpl) appMod.findViewObject("DaTrackingProcessDocumentsView1");
        Row newRow = fileVo.createRow();
        newRow.setAttribute("DaTrackingProcessId", daTrackingProcessId);
        //newRow.setAttribute("StepId", stepId);        
        newRow.setAttribute("DocumentName", documentName);
        newRow.setAttribute("DocumentLocation", documentLocation);
        newRow.setAttribute("Description", description);
        fileVo.insertRow(newRow);
        fileVo.getDBTransaction().commit();
        //fileVo.executeQuery();
       }catch(Exception exception){
            System.err.println("Error setting file data in setFileData method");   
       }finally{
           if(appMod != null){
               Configuration.releaseRootApplicationModule(appMod, false);                      
           }   
           fileVo = null; 
       }
    }  
    
    /**Method to set file path, file name, step id and da id * @param name * @param path */
    public void setFileDetails(int stepId, int daId, String documentName, String documentLocation, String description) {
        try{
        ApplicationModule appMod = Configuration.createRootApplicationModule("dats.model.AppModule", "AppModuleLocal");
       DaTrackingProcessDocumentsViewImpl  fileVo = (DaTrackingProcessDocumentsViewImpl) appMod.findViewObject("DaTrackingProcessDocumentsView1");
        Row newRow = fileVo.createRow();
        //newRow.setAttribute("DaTrackingProcessId", daTrackingProcessId);
        newRow.setAttribute("StepId", stepId);    
        newRow.setAttribute("DaId", daId);   
        newRow.setAttribute("DocumentName", documentName);
        newRow.setAttribute("DocumentLocation", documentLocation);
        newRow.setAttribute("Description", description);
        fileVo.insertRow(newRow);
        fileVo.getDBTransaction().commit();
        //fileVo.executeQuery();
        }catch(Exception exception){
           //exception.printStackTrace();
           System.err.println("Error saving Da File details");
        }
    }
}

