package dats.model;

import oracle.jbo.server.ViewDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 17 08:09:39 EAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DisbursementAuthorizationsViewDefImpl extends ViewDefImpl {
    public DisbursementAuthorizationsViewDefImpl(String name) {
        super(name);
    }

    /**
     * This is the default constructor (do not remove).
     */
    public DisbursementAuthorizationsViewDefImpl() {
    }
}

