package dats.model;

import oracle.jbo.ApplicationModule;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.client.Configuration;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 06 15:38:23 EAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DisbursementAuthorizations1ViewRowImpl extends ViewRowImpl {

    public static final int ENTITY_DISBURSEMENTAUTHORIZATIONS1 = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Id,
        DaNumber,
        TotalValue,
        NumberOfBeneficiaries,
        NgoId,
        LoaNumber,
        DistrictId,
        PaymentLocation,
        MoneyVendorId,
        IsActive,
        Description,
        PhaseId,
        InterventionTypeId,
        Phase,
        DisbursementAuthorizations1View,
        DisbursementAuthorizations1View1,
        DisbursementAuthorizations1View2,
        PhasesView1,
        DistrictsView1,
        InterventionTypesView1,
        NgosView1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int ID = AttributesEnum.Id.index();
    public static final int DANUMBER = AttributesEnum.DaNumber.index();
    public static final int TOTALVALUE = AttributesEnum.TotalValue.index();
    public static final int NUMBEROFBENEFICIARIES = AttributesEnum.NumberOfBeneficiaries.index();
    public static final int NGOID = AttributesEnum.NgoId.index();
    public static final int LOANUMBER = AttributesEnum.LoaNumber.index();
    public static final int DISTRICTID = AttributesEnum.DistrictId.index();
    public static final int PAYMENTLOCATION = AttributesEnum.PaymentLocation.index();
    public static final int MONEYVENDORID = AttributesEnum.MoneyVendorId.index();
    public static final int ISACTIVE = AttributesEnum.IsActive.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int PHASEID = AttributesEnum.PhaseId.index();
    public static final int INTERVENTIONTYPEID = AttributesEnum.InterventionTypeId.index();
    public static final int PHASE = AttributesEnum.Phase.index();
    public static final int DISBURSEMENTAUTHORIZATIONS1VIEW = AttributesEnum.DisbursementAuthorizations1View.index();
    public static final int DISBURSEMENTAUTHORIZATIONS1VIEW1 = AttributesEnum.DisbursementAuthorizations1View1.index();
    public static final int DISBURSEMENTAUTHORIZATIONS1VIEW2 = AttributesEnum.DisbursementAuthorizations1View2.index();
    public static final int PHASESVIEW1 = AttributesEnum.PhasesView1.index();
    public static final int DISTRICTSVIEW1 = AttributesEnum.DistrictsView1.index();
    public static final int INTERVENTIONTYPESVIEW1 = AttributesEnum.InterventionTypesView1.index();
    public static final int NGOSVIEW1 = AttributesEnum.NgosView1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DisbursementAuthorizations1ViewRowImpl() {
    }

    /**
     * Gets DisbursementAuthorizations1 entity object.
     * @return the DisbursementAuthorizations1
     */
    public EntityImpl getDisbursementAuthorizations1() {
        return (EntityImpl) getEntity(ENTITY_DISBURSEMENTAUTHORIZATIONS1);
    }

    /**
     * Gets the attribute value for id using the alias name Id.
     * @return the id
     */
    public Integer getId() {
        return (Integer) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for id using the alias name Id.
     * @param value value to set the id
     */
    public void setId(Integer value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for da_number using the alias name DaNumber.
     * @return the da_number
     */
    public String getDaNumber() {
        return (String) getAttributeInternal(DANUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for da_number using the alias name DaNumber.
     * @param value value to set the da_number
     */
    public void setDaNumber(String value) {
        setAttributeInternal(DANUMBER, value);
    }

    /**
     * Gets the attribute value for total_value using the alias name TotalValue.
     * @return the total_value
     */
    public Float getTotalValue() {
        return (Float) getAttributeInternal(TOTALVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for total_value using the alias name TotalValue.
     * @param value value to set the total_value
     */
    public void setTotalValue(Float value) {
        setAttributeInternal(TOTALVALUE, value);
    }

    /**
     * Gets the attribute value for number_of_beneficiaries using the alias name NumberOfBeneficiaries.
     * @return the number_of_beneficiaries
     */
    public Integer getNumberOfBeneficiaries() {
        return (Integer) getAttributeInternal(NUMBEROFBENEFICIARIES);
    }

    /**
     * Sets <code>value</code> as attribute value for number_of_beneficiaries using the alias name NumberOfBeneficiaries.
     * @param value value to set the number_of_beneficiaries
     */
    public void setNumberOfBeneficiaries(Integer value) {
        setAttributeInternal(NUMBEROFBENEFICIARIES, value);
    }

    /**
     * Gets the attribute value for ngo_id using the alias name NgoId.
     * @return the ngo_id
     */
    public Integer getNgoId() {
        return (Integer) getAttributeInternal(NGOID);
    }

    /**
     * Sets <code>value</code> as attribute value for ngo_id using the alias name NgoId.
     * @param value value to set the ngo_id
     */
    public void setNgoId(Integer value) {
        setAttributeInternal(NGOID, value);
    }

    /**
     * Gets the attribute value for loa_number using the alias name LoaNumber.
     * @return the loa_number
     */
    public String getLoaNumber() {
        return (String) getAttributeInternal(LOANUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for loa_number using the alias name LoaNumber.
     * @param value value to set the loa_number
     */
    public void setLoaNumber(String value) {
        setAttributeInternal(LOANUMBER, value);
    }

    /**
     * Gets the attribute value for district_id using the alias name DistrictId.
     * @return the district_id
     */
    public Integer getDistrictId() {
        return (Integer) getAttributeInternal(DISTRICTID);
    }

    /**
     * Sets <code>value</code> as attribute value for district_id using the alias name DistrictId.
     * @param value value to set the district_id
     */
    public void setDistrictId(Integer value) {
        setAttributeInternal(DISTRICTID, value);
    }

    /**
     * Gets the attribute value for payment_location using the alias name PaymentLocation.
     * @return the payment_location
     */
    public String getPaymentLocation() {
        return (String) getAttributeInternal(PAYMENTLOCATION);
    }

    /**
     * Sets <code>value</code> as attribute value for payment_location using the alias name PaymentLocation.
     * @param value value to set the payment_location
     */
    public void setPaymentLocation(String value) {
        setAttributeInternal(PAYMENTLOCATION, value);
    }

    /**
     * Gets the attribute value for money_vendor_id using the alias name MoneyVendorId.
     * @return the money_vendor_id
     */
    public Integer getMoneyVendorId() {
        return (Integer) getAttributeInternal(MONEYVENDORID);
    }

    /**
     * Sets <code>value</code> as attribute value for money_vendor_id using the alias name MoneyVendorId.
     * @param value value to set the money_vendor_id
     */
    public void setMoneyVendorId(Integer value) {
        setAttributeInternal(MONEYVENDORID, value);
    }

    /**
     * Gets the attribute value for is_active using the alias name IsActive.
     * @return the is_active
     */
    public Integer getIsActive() {
        return (Integer) getAttributeInternal(ISACTIVE);
    }

    /**
     * Sets <code>value</code> as attribute value for is_active using the alias name IsActive.
     * @param value value to set the is_active
     */
    public void setIsActive(Integer value) {
        setAttributeInternal(ISACTIVE, value);
    }

    /**
     * Gets the attribute value for description using the alias name Description.
     * @return the description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for description using the alias name Description.
     * @param value value to set the description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for phase_id using the alias name PhaseId.
     * @return the phase_id
     */
    public Integer getPhaseId() {
        return (Integer) getAttributeInternal(PHASEID);
    }

    /**
     * Sets <code>value</code> as attribute value for phase_id using the alias name PhaseId.
     * @param value value to set the phase_id
     */
    public void setPhaseId(Integer value) {
        setAttributeInternal(PHASEID, value);
    }

    /**
     * Gets the attribute value for intervention_type_id using the alias name InterventionTypeId.
     * @return the intervention_type_id
     */
    public Integer getInterventionTypeId() {
        return (Integer) getAttributeInternal(INTERVENTIONTYPEID);
    }

    /**
     * Sets <code>value</code> as attribute value for intervention_type_id using the alias name InterventionTypeId.
     * @param value value to set the intervention_type_id
     */
    public void setInterventionTypeId(Integer value) {
        setAttributeInternal(INTERVENTIONTYPEID, value);
    }

    /**
     * Gets the attribute value for phase using the alias name Phase.
     * @return the phase
     */
    public String getPhase() {
        return (String) getAttributeInternal(PHASE);
    }

    /**
     * Sets <code>value</code> as attribute value for phase using the alias name Phase.
     * @param value value to set the phase
     */
    public void setPhase(String value) {
        setAttributeInternal(PHASE, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link DisbursementAuthorizations1View.
     */
    public RowIterator getDisbursementAuthorizations1View() {
        return (RowIterator) getAttributeInternal(DISBURSEMENTAUTHORIZATIONS1VIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link DisbursementAuthorizations1View1.
     */
    public RowIterator getDisbursementAuthorizations1View1() {
        return (RowIterator) getAttributeInternal(DISBURSEMENTAUTHORIZATIONS1VIEW1);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link DisbursementAuthorizations1View2.
     */
    public RowIterator getDisbursementAuthorizations1View2() {
        return (RowIterator) getAttributeInternal(DISBURSEMENTAUTHORIZATIONS1VIEW2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PhasesView1.
     */
    public RowSet getPhasesView1() {
        return (RowSet) getAttributeInternal(PHASESVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DistrictsView1.
     */
    public RowSet getDistrictsView1() {
        return (RowSet) getAttributeInternal(DISTRICTSVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> InterventionTypesView1.
     */
    public RowSet getInterventionTypesView1() {
        return (RowSet) getAttributeInternal(INTERVENTIONTYPESVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> NgosView1.
     */
    public RowSet getNgosView1() {
        return (RowSet) getAttributeInternal(NGOSVIEW1);
    }


}

