package dats.model;

import java.sql.ResultSet;

import oracle.adf.model.BindingContainer;

import oracle.jbo.ApplicationModule;
import oracle.jbo.Row;
import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.client.Configuration;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 17 08:09:26 EAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DisbursementAuthorizationsViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DisbursementAuthorizationsViewImpl() {
    }

    /**
     * executeQueryForCollection - for custom java data source support.
     */
    @Override
    protected void executeQueryForCollection(Object qc, Object[] params, int noUserParams) {
        super.executeQueryForCollection(qc, params, noUserParams);
    }

    /**
     * hasNextForCollection - for custom java data source support.
     */
    @Override
    protected boolean hasNextForCollection(Object qc) {
        boolean bRet = super.hasNextForCollection(qc);
        return bRet;
    }

    /**
     * createRowFromResultSet - for custom java data source support.
     */
    @Override
    protected ViewRowImpl createRowFromResultSet(Object qc, ResultSet resultSet) {
        ViewRowImpl value = super.createRowFromResultSet(qc, resultSet);
        return value;
    }

    /**
     * getQueryHitCount - for custom java data source support.
     */
    @Override
    public long getQueryHitCount(ViewRowSetImpl viewRowSet) {
        long value = super.getQueryHitCount(viewRowSet);
        return value;
    }

    /**
     * getCappedQueryHitCount - for custom java data source support.
     */
    @Override
    public long getCappedQueryHitCount(ViewRowSetImpl viewRowSet, Row[] masterRows, long oldCap, long cap) {
        long value = super.getCappedQueryHitCount(viewRowSet, masterRows, oldCap, cap);
        return value;
    }
    
    //Get daId for daNumber
    public int getDAId(String daNumber) {
        int daId = 0;
        ApplicationModule appMod =null;        
        DisbursementAuthorizationsViewImpl vo = null;        
        try{
        appMod = Configuration.createRootApplicationModule("dats.model.AppModule", "AppModuleLocal");
        vo = (DisbursementAuthorizationsViewImpl) appMod.findViewObject("DisbursementAuthorizations1View1");
        //Create View criteria
        ViewCriteria viewCriteria = vo.createViewCriteria();
        ViewCriteriaRow viewCriteriaRow = viewCriteria.createViewCriteriaRow();
        viewCriteriaRow.setAttribute("DaNumber", daNumber);
        viewCriteria.add(viewCriteriaRow);
        viewCriteria.setCriteriaMode(ViewCriteria.CRITERIA_MODE_CACHE);
        vo.applyViewCriteria(viewCriteria);
        vo.executeQuery();       
        while (vo.hasNext()) {
            DisbursementAuthorizationsViewRowImpl row = (DisbursementAuthorizationsViewRowImpl) vo.next();
            daId = row.getId();
        }
        }catch(Exception exception){
            System.err.println("Error occurred getting DaId in getDAId(String daNumber) method");
        }finally{
            if(appMod != null){
                Configuration.releaseRootApplicationModule(appMod, false);                      
            }            
        }
        return daId;
    }  
    
    //Get daNumber for daID
   public String getDaNumber(int daId) {
        String daNumber = "";
        ApplicationModule appMod = null;
        DisbursementAuthorizationsViewImpl vo = null;
       try{
         appMod = Configuration.createRootApplicationModule("dats.model.AppModule", "AppModuleLocal");
         vo = (DisbursementAuthorizationsViewImpl) appMod.findViewObject("DisbursementAuthorizations1View1");
        //Create View criteria
        ViewCriteria viewCriteria = vo.createViewCriteria();
        ViewCriteriaRow viewCriteriaRow = viewCriteria.createViewCriteriaRow();
        viewCriteriaRow.setAttribute("Id", daId);      
        viewCriteria.add(viewCriteriaRow);
        viewCriteria.setCriteriaMode(ViewCriteria.CRITERIA_MODE_CACHE);
        vo.applyViewCriteria(viewCriteria);
        vo.executeQuery();        
        while (vo.hasNext()) {
            DisbursementAuthorizationsViewRowImpl row = (DisbursementAuthorizationsViewRowImpl) vo.next();
            daNumber = row.getDaNumber();
        }
       }catch(Exception exception){
          // exception.printStackTrace();
           System.err.println("Error getting DaNumber in getDaNumber(int daId) method");
       }finally{
           if(appMod != null){
               Configuration.releaseRootApplicationModule(appMod, false);                      
           }           
       }
        return daNumber;
    }          
}

