package dats.model;

import oracle.jbo.ApplicationModule;
import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.client.Configuration;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 06 15:38:26 EAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DisbursementAuthorizations1ViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DisbursementAuthorizations1ViewImpl() {
    }

    //Get daId for daNumber
    public int getDAId(String daNumber) {
        int daId = 0;
        ApplicationModule appMod = null;
        DisbursementAuthorizations1ViewImpl vo = null;
        try{
        appMod=Configuration.createRootApplicationModule("dats.model.AppModule", "AppModuleShared");
        vo = (DisbursementAuthorizations1ViewImpl) appMod.findViewObject("DisbursementAuthorizations1View1");
        //Create View criteria
        ViewCriteria viewCriteria = vo.createViewCriteria();
        ViewCriteriaRow viewCriteriaRow = viewCriteria.createViewCriteriaRow();
        viewCriteriaRow.setAttribute("DaNumber", daNumber);
        viewCriteria.add(viewCriteriaRow);
        viewCriteria.setCriteriaMode(ViewCriteria.CRITERIA_MODE_CACHE);
        vo.applyViewCriteria(viewCriteria);
        vo.executeQuery();       
        while (vo.hasNext()) {
            DisbursementAuthorizations1ViewRowImpl row = (DisbursementAuthorizations1ViewRowImpl) vo.next();
            daId = row.getId();
        }
        }catch(Exception excepion){
            System.err.println("Error getting DaId in getDAId(String daNumber) method");
        }finally{
            if(appMod != null){
                Configuration.releaseRootApplicationModule(appMod, false);                      
            }             
        }
        return daId;
    }  
    
    //Get daNumber for daID
    public String getDaNumber(int daId) {
        String daNumber = "";
        ApplicationModule appMod = null;
        DisbursementAuthorizations1ViewImpl vo = null;
       try{
        appMod = Configuration.createRootApplicationModule("dats.model.AppModule", "AppModuleLocal");
        vo = (DisbursementAuthorizations1ViewImpl) appMod.findViewObject("DisbursementAuthorizations1View1");
        //Create View criteria
        ViewCriteria viewCriteria = vo.createViewCriteria();
        ViewCriteriaRow viewCriteriaRow = viewCriteria.createViewCriteriaRow();
        viewCriteriaRow.setAttribute("Id", daId);      
        viewCriteria.add(viewCriteriaRow);
        viewCriteria.setCriteriaMode(ViewCriteria.CRITERIA_MODE_CACHE);
        vo.applyViewCriteria(viewCriteria);
        vo.executeQuery();        
        while (vo.hasNext()) {
            DisbursementAuthorizations1ViewRowImpl row = (DisbursementAuthorizations1ViewRowImpl) vo.next();
            daNumber = row.getDaNumber();
        }
       }catch(Exception exception){
           System.err.println("Error gettingDaNumber in String getDaNumber(int daId) method");
       }finally{
           if(appMod != null){
               Configuration.releaseRootApplicationModule(appMod, false);                      
           }            
           vo=null;
       }
        return daNumber;
    }     
}

