package dats.model;

import oracle.jbo.server.ViewDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 17 10:28:20 EAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DistrictsViewDefImpl extends ViewDefImpl {
    public DistrictsViewDefImpl(String name) {
        super(name);
    }

    /**
     * This is the default constructor (do not remove).
     */
    public DistrictsViewDefImpl() {
    }
}

