package dats.model;

import oracle.jbo.RowSetIterator;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 13 11:52:35 EAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LoginUsersViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LoginUsersViewImpl() {
    }
    
    public int changePassword(String username, String oldPassword, String newPassword){
           int status = 0;
            RowSetIterator rowsetIterator = this.createRowSetIterator(null);
            LoginUsersViewRowImpl row = new LoginUsersViewRowImpl();
            boolean userExists = false;
            if(username != null){
                try{
                    while(rowsetIterator.hasNext()){
                        row = (LoginUsersViewRowImpl) rowsetIterator.next();
                        if(row.getUsername().equals(username) && row.getPassWord().equals(oldPassword)){
                            row.setPassWord(newPassword);
                            this.getDBTransaction().commit();
                            status = 1;//success
                        }else{                           
                            status = -1;  //Username or password is incorrect
                        }
                    }
                }catch(Exception exception){
                    System.err.println("Error changing password");
                    status = -2;//exception
                }               
            }
        return status;
    }
    
 
}

