package dats.model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 12 11:22:50 EAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RatesViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RatesViewImpl() {
    }
}

